config/routes.rb
Rails.application.routes.draw do
 root 'demographics#show'
 	get 'demographics/about' => 'demographics#about', as: "about"
  get 'demographics/index' => 'demographics#index', as: "demographics"
  get 'demographics/json' => 'demographics#json', as: "json"


end

app/models/death.rb
class Death < ActiveRecord::Base
	validates :cause, uniqueness: true, presence: true

  has_many :figures, dependent: :destroy
  has_many :demographics, through: :figures
end

app/models/demographic.rb
class Demographic < ActiveRecord::Base
	validates :state, uniqueness: false, presence: true
	validates :age, uniqueness: false, presence: true
	validates :race, uniqueness: false, presence: true
	validates :ethnicity, uniqueness: false, presence: true
	validates :sex, uniqueness: false, presence: true
	validates :year, uniqueness: false, presence: true

  has_many :figures, dependent: :destroy
  has_many :deaths, through: :figures 

 #  def self.to_csv(options = {})
	#   CSV.generate(options) do |csv|
	#     csv << column_names
	#     all.each do |product|
	#       csv << demographic.attributes.values_at(*column_names)
	#     end
	#   end
	# end
end

app/models/figure.rb
class Figure < ActiveRecord::Base
  validates :number, presence: true, uniqueness: false
  validates :percent, presence: true, uniqueness: false

  belongs_to :death
  belongs_to :demographic

  def self.search(query)
  	where("demographic like ?", "%#{query}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demographics_controller.rb
class DemographicsController < ApplicationController
 
  def index
  	@search=Demographic.search(params[:q])
  	@results = @search.result
  	@search.state_cont = 'Open' && @search.race_cont = 'Open' && @search.ethnicity_cont = 'Open' && @search.sex_cont = 'Open' && @search.age_cont = 'Open' unless params[:q] 
  	@demographics = @search.result
  
  	@figuresYears = [];
  	@deaths = []
  	# add figure rows to be accessible with gon
  	unless params[:q] == nil 
	  	@search.result.each do |dem|
				@figures = Figure.find_by_sql "SELECT * FROM figures WHERE demographic_id = " + dem.id.to_s
				@figuresYears.push(@figures)
			end
		end
	
		# add death rows to be accessible with gon
		unless @figuresYears[0] == nil;
		 	@figuresYears[0].each do |figure|
		 		@death = Death.find_by_sql "SELECT * FROM deaths WHERE id = " + figure.death_id.to_s
				@deaths.push(@death[0])
			end
		end
		#
		
		@data = {
			demographics: @demographics,
			deaths: @deaths,
			figuresYears: @figuresYears
		};

		gon.demographics = @demographics
		gon.deaths = @deaths
		gon.figYears = @figuresYears
		
		# As API
		respond_to do |format|
			format.html
			format.json {
				render json: @data
			}
		end
	end

	def show
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demographics_helper.rb
module DemographicsHelper
end

app/views/demographics/about.html.erb
<h2>About Death, Be Not Unknown</h2>
<p>It's impossible to predict how we will meet our ends. But there is certainly plenty to speculate on.</p>
<p><em>Death, Be Not Unknown</em> was conceived as a way to make American mortality statistics from the Center for Disease Control and Prevention (CDC) more accessible and readily comprehensible.</p>
<p>Because of the restrictions surrounding publicly available mortality data, only the top twenty causes were included in the app's database. All data was laboriously retrieved from the CDC's WISQARS database, about which you can find <a href="http://www.cdc.gov/injury/wisqars/index.html" target="_blank">more information here</a>. If you'd like to see more in-depth stats, <a href="http://wonder.cdc.gov/" target="_blank">visit the CDC's WONDER database</a>, which includes county-level data.</p> 

<p>Using the app is easy. Just select a state and enter characteristics of interest (race, ethnicity, sex, and age as defined by the CDC). Hover over the resulting bubbles to view cause of death, that causes's corresponding percentage of total deaths, and the number of people within that group who died from that cause.</p>

<p>This is a personal project of Rebecca Kilberg. Feel free to <a href="https://github.com/kilbergr/MortalityApp" target="_blank">check out my github repository</a> for this project.</p>

<p>The title of the app is a reference to the classic sonnet <em>Death, Be Not Proud</em> (<a href="http://www.poetryfoundation.org/poem/173363" target="_blank">read the poem here</a>).</p>

<p>Please note, this app is in no way meant to serve as a death prediction tool.</p>

<button class="ui inverted grey button"><%= link_to "Home", demographics_path %></button>

app/views/demographics/index.html.erb
<h1 style="text-align:center">How Will This All End?</h1>
<div class="corner"><%= link_to "About/User's Guide", about_path %></div>
<div id = "map" class="clickable"></div>
<!-- <div id="usa" class="fa fa-globe"></div> -->
<!-- Modal for choosing demographic characteristics -->
<div id="blackScreen">
<div id ="pick" class="ui basic modal">
<!-- option picker section of modal -->
  <i class="close icon"></i>
  	
 <div id="options">
  <%=search_form_for @search, :html => {:id=> "form_id"} do |f|  %>

		<div id="searchForm">
			<input type="hidden" id="q_state_eq" value="">
			<%= f.label(:ethnicity_eq, "Hispanic Origin:", {:class => 'label'}) %>
			<%= f.select(:ethnicity_eq, ['All', 'Non-Hispanic', 'Hispanic'], {}, {:class => 'ui selection dropdown'}) %>
			<!-- <%= f.label(:race_eq, "Race:", {:class => 'label'}) %> -->
			<%= f.select(:race_eq, ['All Races', 'White', 'Black', 'Am Indian/AK Native', 'Asian/Pac Islander', 'Other Races'], {}, {:class => 'ui selection dropdown'}) %>
			<!-- <%= f.label(:sex_eq, "Sex:", {:class => 'label'}) %> -->
			<%= f.select(:sex_eq, ['Both Sexes', 'Females', 'Males'], {}, {:class => 'ui selection dropdown'}) %>
			<!-- <%= f.label(:age_eq, "Age (Years):", {:class => 'label'}) %> -->
			<%= f.select(:age_eq, ['All Ages', '<1', '5-9', '10-14', '15-24', '25-34', '35-44', '45-54', '55-64', '65-74', '75-84', '85+'], {}, {:class => 'ui selection dropdown'}) %>
			<%= f.submit "Search", :id=> "submitMe", :class=>'ui inverted violet button'%>

		</div>
	<% end %>
	</div>

<!-- Bubble viz section -->
<div id="showBubbles">
 
	<button class="ui inverted grey button" id="click1999">1999</button>
	<button class="ui inverted grey button" id="click2000">2000</button>
	<button class="ui inverted grey button" id="click2001">2001</button>
	<button class="ui inverted grey button" id="click2002">2002</button>
	<button class="ui inverted grey button" id="click2003">2003</button>
	<button class="ui inverted grey button" id="click2004">2004</button>
	<button class="ui inverted grey button" id="click2005">2005</button>
	<button class="ui inverted grey button" id="click2006">2006</button>
	<button class="ui inverted grey button" id="click2007">2007</button>
	<button class="ui inverted grey button" id="click2008">2008</button>
	<button class="ui inverted grey button" id="click2009">2009</button>
	<button class="ui inverted grey button" id="click2010">2010</button>
	<button class="ui inverted grey button" id="click2011">2011</button>
	<button class="ui inverted grey button" id="click2012">2012</button>
	<button class="ui inverted grey button" id="click2013">2013</button>
	<button class="ui inverted violet button" id="changeDem">Clear</button>	
		<div id="simpleChart"></div>
		
	</div>
</div>
	<div class="slider"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Death, Be Not Unknown</title>
  <%= include_gon(:init => true) %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>

  	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
   <!-- Icons -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<!-- D3 -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8" http-equiv="encoding"></script>
	<!-- Topojson -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19/topojson.min.js"></script>
    <!-- Datamaps -->
  <script src="/datamaps.usa.min.js"></script>
    <!-- Google font -->
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,700' rel='stylesheet' type='text/css'>
  
  <link rel="stylesheet" href="/semantic-ui-modal/modal.css">

</head>
<body>

<%= yield %>

</body>
</html>